lidar:
  - parent_frame_id: /base_link
    frame_id: /middle_lidar
    device_type: RS80
    x: 0
    y: 0
    z: 2.066000000000007
    roll: 0.008726646500000003
    pitch: -0.00244346102
    yaw: -1.57079637

  - parent_frame_id: /middle_lidar
    frame_id: /left_lidar
    device_type: RSBP
    x: -0.722
    y: 0.09
    z: -0.262
    roll: -1.25454270084
    pitch: -0.009075712360000002
    yaw: 1.56416411866

  - parent_frame_id: /middle_lidar
    frame_id: /right_lidar
    device_type: RSBP
    x: 0.665
    y: -0.008
    z: -0.2729999999999999
    roll: 1.273915856070002
    pitch: 0.01099557459
    yaw: 1.57830128599
#  - parent_frame_id: /middle_lidar
#    frame_id: /back_lidar
#    device_type: RSM1
#    x: -1.185
#    y: 0.116
#    z: 0.008999999999999999
#    roll: -0.00401425739
#    pitch: 0.07347836353000001
#    yaw: -3.118030794450001
base:
  frame_id: /base_link

#odometry:
#  frame_id: /odometry



imu:
  parent_frame_id: /base_link
  frame_id: /imu
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0

gnss:
  parent_frame_id: /base_link
  frame_id: /gnss
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0

odom:
  parent_frame_id: /base_link
  frame_id: /odom
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0
